from typing import Protocol, List, Optional
from database.models import Deputado, Despesa, Proposicao, Artigo


class CamaraRepositoryProtocol(Protocol):
    """Interface para persistência de dados da Câmara."""

    # ─── Deputados ────────────────────────────────────────────

    def salvar_deputado(self, deputado: Deputado) -> None: ...

    def deputado_existe(self, deputado_id: int) -> bool: ...

    def obter_deputado(self, deputado_id: int) -> Optional[Deputado]: ...

    def listar_ids_deputados(self) -> List[int]: ...

    # ─── Despesas ─────────────────────────────────────────────

    def salvar_despesa(self, despesa: Despesa) -> None: ...

    def despesa_existe(self, cod_documento: int) -> bool: ...

    # ─── Proposições ──────────────────────────────────────────

    def salvar_proposicao(self, proposicao: Proposicao) -> None: ...

    def proposicao_existe(self, proposicao_id: int) -> bool: ...

    def obter_ultimo_id_proposicao(self) -> Optional[int]: ...

    def listar_ids_proposicoes(self) -> List[int]: ...

    def listar_proposicoes_sem_autores(self, limit: Optional[int] = None) -> List[int]: ...

    # ─── Artigos ──────────────────────────────────────────────

    def salvar_artigo(self, artigo: Artigo) -> None: ...

    def artigo_existe_para_proposicao(self, id_proposicao: int) -> bool: ...

    def obter_artigo_por_proposicao(self, id_proposicao: int) -> Optional[Artigo]: ...

    def listar_artigos(self, limit: Optional[int] = None) -> List[Artigo]: ...


class ArtigosRepositoryProtocol(Protocol):
    """Interface para persistência de artigos gerados."""

    def salvar_artigo(self, artigo: Artigo) -> None: ...

    def artigo_existe_para_proposicao(self, id_proposicao: int) -> bool: ...

    def obter_artigo_por_proposicao(self, id_proposicao: int) -> Optional[Artigo]: ...

    def listar_artigos(self, limit: Optional[int] = None) -> List[Artigo]: ...